"use client";

import { useState } from "react";
import { uploadLogo } from "@/app/actions/settings";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { toast } from "sonner";
import { Loader2, Upload } from "lucide-react";
import Image from "next/image";

interface AdminSettingsProps {
    currentLogoUrl?: string | null;
}

export function AdminSettings({ currentLogoUrl }: AdminSettingsProps) {
    const [isUploading, setIsUploading] = useState(false);
    const [preview, setPreview] = useState<string | null>(currentLogoUrl || null);

    async function handleUpload(e: React.FormEvent<HTMLFormElement>) {
        e.preventDefault();
        const formData = new FormData(e.currentTarget);
        const file = formData.get("file") as File;

        if (!file || file.size === 0) {
            toast.error("Please select a file");
            return;
        }

        if (file.size > 2 * 1024 * 1024) { // 2MB limit
             toast.error("File size must be under 2MB");
             return;
        }

        setIsUploading(true);
        try {
            const result = await uploadLogo(formData);
            if (result.success) {
                toast.success("Logo uploaded successfully");
                // Create local preview
                const objectUrl = URL.createObjectURL(file);
                setPreview(objectUrl);
            } else {
                toast.error(result.error || "Upload failed");
            }
        } catch (error) {
            toast.error("Something went wrong");
        } finally {
            setIsUploading(false);
        }
    }

    return (
        <Card>
            <CardHeader>
                <CardTitle>Global QR Code Logo</CardTitle>
                <CardDescription>
                    This logo will be placed in the center of QR codes generated by the system.
                    Recommended size: 128x128px, PNG or SVG.
                </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
                {preview && (
                    <div className="border rounded-md p-4 w-fit bg-white/5">
                        <Label className="mb-2 block text-muted-foreground">Current Logo</Label>
                        <div className="relative h-24 w-24">
                            <Image 
                                src={preview} 
                                alt="QR Logo" 
                                fill 
                                className="object-contain" 
                                unoptimized // Since we might use blob or R2 proxy
                            />
                        </div>
                    </div>
                )}

                <form onSubmit={handleUpload} className="space-y-4">
                    <div className="grid w-full max-w-sm items-center gap-1.5">
                        <Label htmlFor="logo">Upload New Logo</Label>
                        <Input id="logo" name="file" type="file" accept="image/png,image/jpeg,image/svg+xml" />
                    </div>
                    <Button type="submit" disabled={isUploading}>
                        {isUploading ? (
                            <>
                                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                                Uploading...
                            </>
                        ) : (
                            <>
                                <Upload className="mr-2 h-4 w-4" />
                                Upload Logo
                            </>
                        )}
                    </Button>
                </form>
            </CardContent>
        </Card>
    );
}
